import Head from 'next/head'
import Banner from '../components/Banner'
import styles from "../styles/Home.module.css";
import Testimonials from '../components/Testimonials';
import Image from 'next/image';
import Image1 from "../images/relax1.jpg";
import Image2 from "../images/relax2.jpg";
import Steps from '../components/Steps';
import { reviews } from "../utils/reviews";
import { steps } from "../utils/steps";
import MainLayout from "../layouts/MainLayout"


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>QuickBuck</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
         <Banner />
        <section className={styles.section_container}>
          <div className={styles.container_topdiv}>
            <div className={styles.topdiv_div}>
              <h4 className={styles.topdiv_h4}>Our Freelancers are expereinced. They are ready to make your everyday life easier.</h4>
              <p className={styles.topdiv_p}>
                Get back time for what you love without breaking the bank.
              </p>
            </div>

            <div className={styles.topdiv_image_container}>
              <Image 
                src={Image1}
                alt="Picture of the author"
               className={styles.topdiv_image}
              />
              <Image 
                src={Image2}
                alt="Picture of the author"
               className={styles.topdiv_image}
              />
             
            </div>
          </div>

          <div className={styles.steps_container}>
            <div>
              <h2 className={styles.steps_h2}>How it works</h2>
              <p className={styles.steps_p}>{`It's easy to get started. Just follow these simple steps.`}</p>
            </div>
            <Steps 
              steps={steps}
            />
          </div>

          <div className={styles.testimonials}>
            <div>
              <Testimonials 
                testimonials={reviews}
              />
            </div>
          </div>

        </section>

      </main>

      

    </div>
  )
}

Home.getLayout = function getLayout(page) {
  return (
    <MainLayout>
      {page}
    </MainLayout>
  )
}